%Read me--------------
% Script for automated processing ASCII files generated by topspin command convbin2asc. This script has initially been made to
% integrate 1H spectra in position of EDTA/Ca2 and EDTA/Mg2 complexes in
% range from 2.4098 to 2.4888 ppm for Ca2 (red in plots) and from 2.5500 ppm to 2.6183 for
% Mg2 (green in plots). 
% First, process spectra in topspin using commands ‘efp’, ‘apk’ and ‘absn’. 
% (It is recommended to write user script by using command 'edau' and use ‘qumulti’ afterwards to run this user script for all 
% spectra at once). Afterwards, use command ‘qumulti convbin2asc [numbers of expno]’ to export all spectra into asci files. 
% How to use this script:
% Copy this .m file into the parent folder containing your 1H experiments. Make sure all of the spectra are processed and 
% exported into asci files. Open this .m file in Matlab and click the big green RUN button. 
% Outputs:
% Figures (.png files) of individual peaks with the marked integrated area (red line). One .xlsx file containing the name of 
% the experiment (parsed from the title) and integral of the peak.
% Tested on:
% Matlab R2020a (with Bioinformatics and Signal processing toolbox), TopSpin 4.0.8 and Microsoft Excel 2016 v 16.0.5
% Contact author: mar.jakubec@gmail.com
%--------------------
clear all 
close all


% Import spectra ascii files

files = dir('*\pdata\*\ascii-spec.txt');
files_names = dir('*\pdata\*\title');


for i = 1:size(files,1)
addpath(files(i).folder)
out{i} = dlmread(files(1).name,',', 1, 0);
% Import identifier
name{i} = fileread(files_names(i).name);
rmpath(files(i).folder) 
end

%Peak finding + integration

for i = 1:size(files,1)
mtest(:,1) = out{i}(:,4);
mtest(:,2) = out{i}(:,2);
mtest = mtest(out{i}(:,4) > 2.38 & out{i}(:,4)<2.7,:);
mtest = flipud(mtest);
x = mtest(:,1);
y = mtest(:,2);
figure('units','normalized','outerposition',[0 0 0.7 0.8],'visible','off');
hold on
plot(x,y,'LineWidth',2)
set(gca,'XDir','reverse')
left_lim = 2.4098;
right_lim = 2.4888;
ind_int = mtest(:,1) > left_lim & mtest(:,1) <  right_lim;

intg = sum(mtest(ind_int,2));
xlim ([2.38 2.64])
plot(mtest(ind_int,1),zeros(size(mtest(ind_int,1),1)),'r','Linewidth',2);
legend('off')

l_lim2 = 2.5500;
r_lim2 = 2.6183;

ind_int2 = mtest(:,1) > l_lim2 & mtest(:,1) < r_lim2;
intg2 = sum(mtest(ind_int2,2));
plot(mtest(ind_int2,1),zeros(size(mtest(ind_int2,1),1)),'g','Linewidth',2);

if max(mtest(:,2))< 1E5
ylim ([0 1E5])
else
ylim ([0 inf])
end

title(sprintf('%s',name{i}))
xlabel('ppm')
ylabel('intensity')

to_scan = files(i).folder(end-12:end);
ind = regexp(to_scan,'\\');
th = sscanf(to_scan(ind(1):ind(2)),'%*[^0123456789]%d');

print(sprintf('%d EDTA Complex.png',th(1)),'-dpng')
close all 
res_int(i,1) = intg;
res_int2(i,1) = intg2;
clear mtest th h 

end
% 
% % Export resuts in table
names = char(name);
T = table(names,res_int,res_int2);
T.Properties.VariableNames{'res_int2'} = 'Integral EDTA-Mg';
T.Properties.VariableNames{'res_int'} = 'Integral EDTA-Ca';
T.Properties.VariableNames{'names'} = 'Experiment';


writetable(T,'Results EDTA Complex.xlsx')

clear all 
close all 
% End





